export const MOCK_POTENTIAL_MATCHES = [
  {
    type: "Family",
    props: {
      id: "mock_family_1",
      userId: "mock_user_1",
      name: "David C.",
      hasNanny: false,
      childrenCount: 1,
      ages: [0.1], // 1 month
      careType: "part-time care",
      schedule: {
        monday: false,
        tuesday: true,
        wednesday: true,
        thursday: true,
        friday: false,
        saturday: false,
        sunday: false,
      },
      location: { city: "Piedmont" },
      sharedRate: "~$17.50 – $20/hr per family",
      soloRate: "$35 – $40/hr",
      hosting: "rotating between homes",
      start: "March 8, 2027",
      img: "",
      isTeaser: false,
      status: "none",
    }
  },
  {
    type: "Nanny",
    props: {
      id: "mock_nanny_1",
      userId: "mock_user_2",
      name: "Melissa L.",
      hasFamily: true,
      experience: "5+ years",
      ages: ["infants (0–1)", "toddlers (1–3)"],
      careType: "full-time care",
      schedule: {
        monday: true,
        tuesday: true,
        wednesday: true,
        thursday: true,
        friday: true,
        saturday: false,
        sunday: false,
      },
      location: { city: "Oakland" },
      soloRate: "$40 – $45/hr",
      sharedRate: "Combined rate for 2 families",
      start: "October 12, 2026",
      img: "",
      isTeaser: false,
      status: "none",
    }
  },
  {
    type: "Family",
    props: {
      id: "mock_family_2",
      userId: "mock_user_3",
      name: "Sarah M.",
      hasNanny: true,
      childrenCount: 2,
      ages: [2, 4], 
      careType: "full-time care",
      schedule: {
        monday: true,
        tuesday: true,
        wednesday: true,
        thursday: true,
        friday: true,
        saturday: false,
        sunday: false,
      },
      location: { city: "Rockridge" },
      sharedRate: "~$18 – $22/hr per family",
      soloRate: "$36 – $44/hr",
      hosting: "Your home",
      start: "September 1, 2026",
      img: "",
      isTeaser: false,
      status: "none",
    }
  },
  {
    type: "Nanny",
    props: {
      id: "mock_nanny_2",
      userId: "mock_user_4",
      name: "Jessica T.",
      hasFamily: false,
      experience: "8+ years",
      ages: ["toddlers (1–3)", "preschool (3–5)"],
      careType: "part-time care",
      schedule: {
        monday: true,
        tuesday: false,
        wednesday: true,
        thursday: false,
        friday: true,
        saturday: false,
        sunday: false,
      },
      location: { city: "Berkeley" },
      soloRate: "$38 – $42/hr",
      sharedRate: "Combined rate for 2 families",
      start: "August 15, 2026",
      img: "",
      isTeaser: false,
      status: "none",
    }
  },
  {
    type: "Family",
    props: {
      id: "mock_family_3",
      userId: "mock_user_5",
      name: "Alex W.",
      hasNanny: false,
      childrenCount: 1,
      ages: [1], 
      careType: "full-time care",
      schedule: {
        monday: true,
        tuesday: true,
        wednesday: true,
        thursday: true,
        friday: true,
        saturday: false,
        sunday: false,
      },
      location: { city: "San Francisco" },
      sharedRate: "~$19 – $23/hr per family",
      soloRate: "$38 – $46/hr",
      hosting: "flexible",
      start: "October 1, 2026",
      img: "",
      isTeaser: false,
      status: "none",
    }
  },
  {
    type: "Family",
    props: {
      id: "mock_family_4",
      userId: "mock_user_6",
      name: "Taylor R.",
      hasNanny: false,
      childrenCount: 2,
      ages: [3, 5], 
      careType: "part-time care",
      schedule: {
        monday: true,
        tuesday: false,
        wednesday: true,
        thursday: false,
        friday: true,
        saturday: false,
        sunday: false,
      },
      location: { city: "San Leandro" },
      sharedRate: "~$16 – $20/hr per family",
      soloRate: "$32 – $40/hr",
      hosting: "My home",
      start: "Flexible",
      img: "",
      isTeaser: false,
      status: "none",
    }
  }
];

export const MOCK_CAREGIVER_MATCHES = MOCK_POTENTIAL_MATCHES.filter(m => m.type === "Family");
